version: 2


models:
  - name: dim_client
  description: The client dimenion table. This includes all clients that ever placed a request
  columns:
    - name: client_id
      tests:
        - unique
        - not_null
    - name: client_address
      description: The encrypted address of a client
    - name: client_city
      description: The city where a client lives
    - name: phone
      description: The encrypted phone number of a client
    - name: client_name
      description: The encrypted name of a client