SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    REQUEST_AT AS REQUEST_TS,
    CAST(CLIENT_ID AS STRING) AS CLIENT_ID,
    NAME,
    ADDRESS,
    CITY,
    PHONE,
    CAST(PET_ID AS STRING) AS PET_ID,
    PET_NAME,
    REQUEST_DAY_FROM AS START_WALK_TS,
    REQUEST_DURATION AS WALK_MINUTES,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{ source('box', 'requests') }}