version: 2

sources:
  - name: google_drive_load
    database: LOAD
    schema: GOOGLE_DRIVE_LOAD
    tables:
      - name: EXPENSES
        loaded_at_field: _FIVETRAN_SYNCED
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 3
            period: day

      - name: HR_JOINS
        loaded_at_field: _FIVETRAN_SYNCED
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 3
            period: day

      - name: HR_QUITS
        loaded_at_field: _FIVETRAN_SYNCED
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 3
            period: day

      - name: RETURNS
        loaded_at_field: _FIVETRAN_SYNCED
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 3
            period: day

  - name: web_schema
    database: LOAD
    schema: WEB_SCHEMA
    tables:
      - name: ITEM_VIEWS
        loaded_at_field: _FIVETRAN_SYNCED
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 3
            period: day

      - name: ORDERS
        loaded_at_field: _FIVETRAN_SYNCED
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 3
            period: day

      - name: PAGE_VIEWS
        loaded_at_field: _FIVETRAN_SYNCED
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 3
            period: day

      - name: SESSIONS
        loaded_at_field: _FIVETRAN_SYNCED
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 3
            period: day
            